# 1. Utiliser une image Nginx alpine
FROM nginx:alpine

# 2. Copier les fichiers statiques (index.html) dans le dossier web par défaut de Nginx
COPY . /usr/share/nginx/html

# 3. Exposer le port 80 (le port par défaut de Nginx à l'intérieur du conteneur)
EXPOSE 80